name: Demo
description: ''
version: 1.0.2
author: virgilletters@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demo
  parentArtefactID: virgillettersgmail.com_team
  buildSystem: wheel
  author: null
  createdAt: '2023-09-20 16:32:52'
pipelines:
  pipelines/demo_etl_pipeline:
    name: demo_etl_pipeline
    description: ''
    author: virgilletters@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-20 16:32:52'
    datasets:
      inputs:
      - datasets/virgil_poc_dataset
      outputs:
      - datasets/virgil_poc_write
    subgraphs: []
    dependencies: {}
datasets:
  datasets/virgil_poc_dataset:
    name: virgil_poc_dataset
    description: ''
    author: virgilletters@gmail.com
    createdAt: '2023-09-27 06:42:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 4877
        datasetType: File
        description: ''
        author: virgilletters@gmail.com
        createdAt: '2023-09-27 06:42:08'
  datasets/virgil_poc_write:
    name: virgil_poc_write
    description: ''
    author: virgilletters@gmail.com
    createdAt: '2023-09-27 06:52:53'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 4877
        datasetType: File
        description: ''
        author: virgilletters@gmail.com
        createdAt: '2023-09-27 06:52:53'
templates: {}
jobs:
  jobs/virgil_job_schedule:
    name: virgil_job_schedule
    description: ''
    fabricUID: 4877
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/demo_etl_pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-09-27 09:14:29'
    author: virgilletters@gmail.com
functions:
  author: null
  createdAt: '2023-09-20 16:32:52'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
